buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.0'
    }
}

allprojects {

    ext {
        appName = 'Shattered Pixel Dungeon'
        appPackageName = 'com.shatteredpixel.shatteredpixeldungeon'

        //Full releases gets +2 on version code, needed for an F-Droid quirk
        appVersionCode = 912
        appVersionName = '4.0.0'

        appJavaCompatibility = JavaVersion.VERSION_11

        appAndroidCompileSDK = 36   //Android 15
        appAndroidMinSDK = 21       //Android 5.0
        appAndroidTargetSDK = 36    //Android 15

        gdxVersion = '1.14.0'
        gdxControllersVersion = '2.2.4'
        robovmVersion = '2.3.24'
    }
    version = appVersionName

    repositories {
        google()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }

}