name: Build JAR and APK

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Create JKS from secret
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "android-release.jks"
          fileDir: ${{ runner.workspace }}
          encodedString: ${{ secrets.JKS_FILE_B64 }}

      - name: Build desktop jar and android apk
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            desktop:release
            android:packageRelease
            -PRELEASE_STORE_FILE=${{ runner.workspace }}/android-release.jks
            -PRELEASE_STORE_PASSWORD=${{ secrets.JKS_PASS }}
            -PRELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
            -PRELEASE_KEY_PASSWORD=${{ secrets.KEY_PASS }}

      - name: Upload desktop jar
        uses: actions/upload-artifact@v3
        with:
          name: "spd-${{ github.ref_name }}-${{ github.run_number }}.jar"
          path: desktop/build/libs/desktop-*.jar
          retention-days: 2

      - name: Upload android APK
        uses: actions/upload-artifact@v3
        with:
          name: "spd-${{ github.ref_name }}-${{ github.run_number }}.apk"
          path: android/build/outputs/apk/release/android-release.apk
          retention-days: 2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            desktop/build/libs/desktop-*.jar
            android/build/outputs/apk/release/android-release.apk
